### ISSUE TITLE
question permissions

### ISSUE THREAD

**Issue by Zarkness2** [XiaMoZhiShi/MorphPlugin#10]
I have a question and that is that I want to give the users the disguises by permission what would be the permission that I would have to give them so that for example they can transform into the allay?

**Comment by Zarkness2** [comment]
another question is it possible to put that the skills and abilities are a permission? 
each skill is a different permission and each ability is the same.

example that the fire_resistance ability that has the wither for example is feathermorph.ability.fire_resistance.wither and only the fire_resistance would work in the wither and it would be the same but for the skills of each mob.

I am making an rpg and I would like that they can transform but they have to unlock both the skills and the skills of each mob and if they go by permission apart from having to put them in the skills.json I can do that system perfectly.

**Comment by Zarkness2** [comment]
then in the villager it would be cool that people can choose which villager they want to be, either trade and type of villager by biome, obviously it would be nice to also go by permissions.

**Comment by MATRIX-feather** [comment]
> I have a question and that is that I want to give the users the disguises by permission what would be the permission that I would have to give them so that for example they can transform into the allay?

It's `xiamomc.morph.morph.as.minecraft.allay`.

These permissions' format is `xiamomc.morph.morph.as.<Disguise ID>`. For example, the permission for Sheep(`minecraft:sheep`) disguise is `xiamomc.morph.morph.as.minecraft.sheep` and for Player disguise Notch(`player:Notch`) is `xiamomc.morph.morph.as.player.Notch`.

You can find other permission usages on our [Wiki](https://github.com/XiaMoZhiShi/FeatherMorph/wiki/Permissions)

> another question is it possible to put that the skills and abilities are a permission?
> each skill is a different permission and each ability is the same.

Hmmm, We currently have permission to allow players to use the skill, but we haven't yet for each skill and ability. I'll consider doing this in the next release.

> then in the villager it would be cool that people can choose which villager they want to be, either trade and type of villager by biome, obviously it would be nice to also go by permissions.

Well, this needs some work, as we need to figure out how players can use this feature. And for trade, I would suggest using other plugins that have been made for implementing the trade system, since most of them are more mature and have more features than the ones we would do by ourselves.

**Comment by Zarkness2** [comment]
> then in the villager it would be cool that people can choose which villager they want to be, either trade and type of villager by biome, obviously it would be nice to also go by permissions.

about this would also be good for the different mobs that have variations such as rabbits, parrots etc...

**Comment by Zarkness2** [comment]
> > I have a question and that is that I want to give the users the disguises by permission what would be the permission that I would have to give them so that for example they can transform into the allay?
> 
> It's `xiamomc.morph.morph.as.minecraft.allay`.
> 
> These permissions' format is `xiamomc.morph.morph.as.<Disguise ID>`. For example, the permission for Sheep(`minecraft:sheep`) disguise is `xiamomc.morph.morph.as.minecraft.sheep` and for Player disguise Notch(`player:Notch`) is `xiamomc.morph.morph.as.player.Notch`.
> 
> You can find other permission usages on our [Wiki](https://github.com/XiaMoZhiShi/FeatherMorph/wiki/Permissions)
> 

Ok, thank you very much, I will check the wiki, I gave myself the xiamomc.morph.morph.morph.as.minecraft.wither permission and I couldn't transform I had to run the /fm manage grant <player> <morph> command as well.


> > another question is it possible to put that the skills and abilities are a permission?
> > each skill is a different permission and each ability is the same.
> 
> Hmmm, We currently have permission to allow players to use the skill, but we haven't yet for each skill and ability. I'll consider doing this in the next release.
> 

ok, thank you very much it would be nice if it's like I said in the message per mob and not a global permission.

> > then in the villager it would be cool that people can choose which villager they want to be, either trade and type of villager by biome, obviously it would be nice to also go by permissions.
> 
> Well, this needs some work, as we need to figure out how players can use this feature. And for trade, I would suggest using other plugins that have been made for implementing the trade system, since most of them are more mature and have more features than the ones we would do by ourselves.


the trading thing was my mistake, i didn't mean it, i meant that they can choose what type of villager craft to be and what biome to be the villager from, no need to add any trading or anything like that. 

then just as I asked for the villager that people can choose the trade of the villager to be either bookseller, farmer etc... could be added the same but for the different mobs that have variations such as rabbit, fox, etc...

**Comment by MATRIX-feather** [comment]
> Ok, thank you very much, I will check the wiki, I gave myself the xiamomc.morph.morph.morph.as.minecraft.wither permission and I couldn't transform I had to run the /fm manage grant command as well.

That's probably because you didn't own the disguise of Wither before, also the permission you grant to yourself seems to be wrong, it should be `xiamomc.morph.morph.as.minecraft.wither` (`xiamomc.morph` + `morph.as.minecraft.wither`)

> the trading thing was my mistake, i didn't mean it, i meant that they can choose what type of villager craft to be and what biome to be the villager from, no need to add any trading or anything like that.
> 
> then just as I asked for the villager that people can choose the trade of the villager to be either bookseller, farmer etc... could be added the same but for the different mobs that have variations such as rabbit, fox, etc...

I see... this may need some time for us to do, as I mentioned before, we need to figure out how could(or should?) people use the feature if we implement this.

**Comment by Zarkness2** [comment]
> > Ok, thank you very much, I will check the wiki, I gave myself the xiamomc.morph.morph.morph.as.minecraft.wither permission and I couldn't transform I had to run the /fm manage grant command as well.
> 
> That's probably because you didn't own the disguise of Wither before, also the permission you grant to yourself seems to be wrong, it should be `xiamomc.morph.morph.as.minecraft.wither` (`xiamomc.morph` + `morph.as.minecraft.wither`)
> 

I tried putting the permission that you passed me and I do not unlock it, as I said I have to put /fm manage grant <user> <mob> + then give me permission to be able to transform. 
If I give me only the permission it does not unlock it automatically as if I use the previous command more to be able to transform me.
According to my logic it would be that if I give me the permission I unlock it automatically.
I need to know if you did it this way on purpose if so nothing happens and I put to run the command from console to unlock the npc.

> > the trading thing was my mistake, i didn't mean it, i meant that they can choose what type of villager craft to be and what biome to be the villager from, no need to add any trading or anything like that.
> > then just as I asked for the villager that people can choose the trade of the villager to be either bookseller, farmer etc... could be added the same but for the different mobs that have variations such as rabbit, fox, etc...
> 
> I see... this may need some time for us to do, as I mentioned before, we need to figure out how could(or should?) people use the feature if we implement this.

ok, thank you very much I think they would use it as it allows them to choose what type of villager to be in both trade and biome, and the same for mobs with different variations as maybe they don't want to be an orange fox and want to be white or maybe they want to be a villager with mapmaker trade being a swamp villager.

**Comment by Zarkness2** [comment]
in the skill_item: you can put custom item and not only a vanilla one? for example a head with custom skin, custom name and lore etc... an easy way to add it would be to add support for the custom items of the itemjoin or plugins that allow you to create any kind of custom item

**Comment by MATRIX-feather** [comment]
> According to my logic it would be that if I give me the permission I unlock it automatically.
> I need to know if you did it this way on purpose if so nothing happens and I put to run the command from console to unlock the npc.

Yes, it's on purpose. On one hand, It appears that there isn't an API for us to listen if someone has been granted permission; on the other hand, this plugin is mainly made for survival servers, and it's not a very great idea to unlock all disguises if they have the permissions since these permissions are unlocked by default (Just imagine someone disguises as the Ender Dragon upon their first join...)

> in the skill_item: you can put custom item and not only a vanilla one? for example a head with custom skin, custom name and lore etc... an easy way to add it would be to add support for the custom items of the itemjoin or plugins that allow you to create any kind of custom item

You can change the attribute of an item such as lore and custom name and the plugin will still treat them as the skill item, but limiting to a specific custom item is not possible now. It may come in the future but there are currently no plans for its implementation

**Comment by Zarkness2** [comment]
> > According to my logic it would be that if I give me the permission I unlock it automatically.
> > I need to know if you did it this way on purpose if so nothing happens and I put to run the command from console to unlock the npc.
> 
> Yes, it's on purpose. On one hand, It appears that there isn't an API for us to listen if someone has been granted permission; on the other hand, this plugin is mainly made for survival servers, and it's not a very great idea to unlock all disguises if they have the permissions since these permissions are unlocked by default (Just imagine someone disguises as the Ender Dragon upon their first join...)
> 

ok, thank you very much

> > in the skill_item: you can put custom item and not only a vanilla one? for example a head with custom skin, custom name and lore etc... an easy way to add it would be to add support for the custom items of the itemjoin or plugins that allow you to create any kind of custom item
> 
> You can change the attribute of an item such as lore and custom name and the plugin will still treat them as the skill item, but limiting to a specific custom item is not possible now. It may come in the future but there are currently no plans for its implementation

ok, thank you very much, it's just that even if I give them the item with lore and custom name, they will get a feather and it will work and they will report it to me so I can fix it.

**Comment by MATRIX-feather** [comment]
Permission node for each skill/ability for disguises is now available on [1.0.14](https://github.com/XiaMoZhiShi/FeatherMorph/releases/tag/1.0.14) for testing. The permission node is `xiamomc.morph.<skill/ability>.<disguise ID>.<skill/ability ID>` (`xiamomc.morph` + `...`, replace `:` to `.` in the IDs)

Specifying variants for disguises like cat and villager, however, in the last week, I still couldn't find a good way to implement this on both the server and the client side, so we (me and several people who help me) decided to hang this idea for now until someone could contribute some code about this.

**Comment by Zarkness2** [comment]
ok, thank you very much, no problem, I'll try it now.

for the ability/skills permission I have to put also in the skills.json the ability/skill?

**Comment by MATRIX-feather** [comment]
> for the ability/skills permission I have to put also in the skills.json the ability/skill?

No, just set for players using the permission plugin you use and you are good to go ;)

And also please notice that there is a known bug that they still do the apply for players in 1.0.14. A initial workaround has been made and you can download the patched version (`Build#1031`) on our Actions page > <

**Comment by Zarkness2** [comment]
I am testing the permissions issue and I need to put in the skills.json the skills and abilities, to fly test with the permissions. 

xiamomc.morph.skill.minecraft.wither.morph.can_fly
xiamomc.morph.ability.minecraft.wither.morph.can_fly 
xiamomc.morph.can_fly

the only one that worked for me to fly was the third one i don't want them to get the can_fly permission and be able to fly with all of them but need the second permission since it's for each mob.

I also tried setting the xiamomc.morph.ability.minecraft.wither.morph.fire_resistance permission to false and it didn't remove the fire resistance effect.

I have the permissions that appear in the image, I just don't know if it's me or the plugin. 

for the fire resistance I just found that it is xiamomc.morph.skill.minecraft.wither.morph.fire_resistance when it is not a skill but an ability.

![image](https://github.com/XiaMoZhiShi/FeatherMorph/assets/48263644/1fd7e2f7-81e2-44ca-b353-53c493dddb73)

**Comment by MATRIX-feather** [comment]
Try [#1032](https://github.com/XiaMoZhiShi/FeatherMorph/actions/runs/8641158254), it should fix the issue.

**Comment by Zarkness2** [comment]
the fly permission remains the same, the permission to remove the bossbar the same I repeat I do not know if it's me or it's something of the plugin, if you want I pass the plugin config files that I have for you to test


suggestion for when version 1.20.5 comes out stable, to be able to edit the size of the mob you are, clearly you need a permission to be able to change between a range example xiamomc.morph.size.1-25 with that you would allow the user to change the size between that range and even be able to set negative size

**Comment by MATRIX-feather** [comment]
Have you tried to disguise again after the permission change? Some of the abilities don't adapt to these changes on the fly, also make sure you have Build #1032 installed

And for 1.20.5 my plan is not to touch the size and pass through it from the player's attribute, so changing the disguises' size won't get supported in the short term

**Comment by Zarkness2** [comment]
> Have you tried to disguise again after the permission change? Some of the abilities don't adapt to these changes on the fly, also make sure you have Build #1032 installed
> 

ok, if I untransform and transform again, it works, but it's not like you told me that I don't need to put in the skill.json, the skills and skills of the mob that with the permission only works, to use the skills and skills it forces me to have them there too.

> And for 1.20.5 my plan is not to touch the size and pass through it from the player's attribute, so changing the disguises' size won't get supported in the short term

ok, thank you very much

**Comment by MATRIX-feather** [comment]
> ok, if I untransform and transform again, it works, but it's not like you told me that I don't need to put in the skill.json

That's a bit strange...Have you touched the skill configuration before? Otherwise it indeed doesn't have to change.

edit: Also if there aren't any further questions, I'll close this issue then?

**Comment by Zarkness2** [comment]
> > ok, if I untransform and transform again, it works, but it's not like you told me that I don't need to put in the skill.json
> 
> That's a bit strange...Have you touched the skill configuration before? Otherwise it indeed doesn't have to change.
> 

The only thing I touched the skills.json was when I didn't have the permissions issue so that my lobby didn't have the skills, and then I reset the whole plugin folder.

> edit: Also if there aren't any further questions, I'll close this issue then?

I'll close the issue
