### ISSUE TITLE
非常好插件，能支持伪装成meg4或meg3模型吗

### ISSUE THREAD

**Issue by TATyKeFei** [XiaMoZhiShi/MorphPlugin#12]
[modelengine 3](https://git.lumine.io/mythiccraft/modelengine/-/wikis/home)
[modelengine 4](https://git.lumine.io/mythiccraft/model-engine-4/-/wikis/home)

**Comment by MATRIX-feather** [comment]
我会试试的，但短期内暂无打算支持modelengine，因为插件在设计时并没有考虑到这些东西，现在适配起来可能会很困难...

**Comment by MATRIX-feather** [comment]
ModelEngine4似乎自带了伪装功能：
https://git.lumine.io/mythiccraft/model-engine-4/-/wikis/MythicMobs/mechanics/model/ModelDisguise
https://git.lumine.io/mythiccraft/model-engine-4/-/wikis/Commands-and-Permissions#disguise-command

**Comment by MATRIX-feather** [comment]
@TATyKeFei

可以测试一下：https://github.com/XiaMoZhiShi/FeatherMorph/actions/runs/9032321784

依赖ModelEngine4，伪装ID是`model4:<模型ID>`

**Comment by TATyKeFei** [comment]
感谢，我测试了一下可以使用😍
