### ISSUE TITLE
Suggestion: Vex targeting other mobs since spawned

### ISSUE THREAD

**Issue by ArduFish** [XiaMoZhiShi/MorphPlugin#14]
Please change the plugin so that vexes summoned by a player disguised as an evoker attack mobs that attacked the summoner and mobs that the summoner attacks since now vexes just fly around useless after the mob is defeated.

**Comment by MATRIX-feather** [comment]
I'll try it, *shouldn't* be very hard to implement.

**Comment by MATRIX-feather** [comment]
Now available for testing on 1.20.6 [latest build](https://github.com/XiaMoZhiShi/FeatherMorph/actions).

After the original target is killed, they will attack the one you last attacked or the one that attacks you.
