### ISSUE TITLE
Not working on minehut

### ISSUE THREAD

**Issue by BluAxoVR** [XiaMoZhiShi/MorphPlugin#21]
In Minehut I tried to load FeatherMorph-1.1.0-beta.6-all.jar, but it doesn't make a folder and it deactivates even though I have ProtocolLib.jar and LibsDisguises.jar

**Comment by MATRIX-feather** [comment]
Please provide a full server log, and check if the server runs 1.21 Paper.

Also since 1.0.0 release, LibsDisguises is no longer needed.
