### ISSUE TITLE
伪装成守卫者后出现全服玩家断开连接而服务器没有崩溃且只有重启服务器后玩家才可以重新进入的情况（而且服务器无法stop关闭，只能强制关闭了）

### ISSUE THREAD

**Issue by cht-ops** [XiaMoZhiShi/MorphPlugin#29]

**Comment by MATRIX-feather** [comment]
看起来是和其他插件冲突了，可以提供一下这些环境信息吗：
- 当前正在使用的服务端（名称和版本）
- 插件版本
- 当前服务器装载的其他插件

**Comment by cht-ops** [comment]
lightingluminal核心1.21.1版本，所用插件的版本是1.3.1，我有cmi，coi，AxInventoryRestore，SkinsRestorer，LuckPerms，minimotd，AuthMe-5.7.0-FORK-Universal，ProtocolLib，BlockLocker，vault-folia-1.7.3，QuickShop-Hikari-6.2.0.7，XConomy-Paper-2.26.3，米饭全家桶全部插件，这些插件与七十二变插件一起使用。

**Comment by MATRIX-feather** [comment]
我这里没有复现，还有些插件是付费的无法测试。

试试更新LightingLuminol和ProtocolLib到最新版本看看能不能解决（ll是 [423183b](https://github.com/LuminolMC/LightingLuminol/releases/tag/1.21.1-423183b)， ProtoclLib是 [5.3.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/5.3.0)）
