### ISSUE TITLE
苦力怕伪装在领地和防爆插件下依然能够爆炸破坏方块

### ISSUE THREAD

**Issue by Phi-2X** [XiaMoZhiShi/MorphPlugin#4]
如题，防爆插件是Boom，领地插件是Residence。其他所有伪装的爆炸都能被防住（恶魂火球，凋零头）
现在只能ban掉了，虽然不是很大的问题提出来就是告诉一下存在

**Comment by MATRIX-feather** [comment]
Residence我之前测试是可以拦截爆炸技能的，应该没有问题。
Boom插件我看有判断要拦截的实体类型，在配置的`global > explosion`下新增对`PLAYER`类型的配置试试？

**Comment by Muyi58317** [comment]
好的解决了

**Comment by Phi-2X** [comment]
好的解决了
