### ISSUE TITLE
residence的nofly flag对伪装不起作用

### ISSUE THREAD

**Issue by Phi-2X** [XiaMoZhiShi/MorphPlugin#5]
即使打开领地的nofly玩家也能飞。把Multiverse-Core中世界选项的的allowFlight改成false也没用。
现在玩家能飞出主城，所以把伪装飞行关了。
但是这样在生存世界就不能飞行，除了用屏障把主城顶封起来再设置worldborder没什么解决办法。
如果可以希望加一个特定世界的配置功能，例如特定世界禁用伪装或者禁用飞行之类的

**Comment by MATRIX-feather** [comment]
>即使打开领地的nofly玩家也能飞。把Multiverse-Core中世界选项的的allowFlight改成false也没用。

Residence和MV设置不生效应该是FM每gt都在检查玩家飞行状态的问题，修起来可能需要一点时间。~~（一开始这么做是为了解决一些插件禁用飞行之后离开管辖范围不会恢复设置导致无法飞行的问题，没想到在领地这翻车了）~~

>如果可以希望加一个特定世界的配置功能，例如特定世界禁用伪装或者禁用飞行之类的

我计划实现特定世界禁用飞行的功能，这周内应该能搞定

**Comment by MATRIX-feather** [comment]
https://github.com/XiaMoZhiShi/FeatherMorph/actions/runs/7139542003

有时间的话试试这个构建，我实现了特定世界禁用飞行的功能。用法是`/fm option nofly_worlds <add|remove> <世界名>`
领地内禁止飞行还需要一点时间

**Comment by MATRIX-feather** [comment]
已在最新构建上完成对nofly和特定世界禁用飞行的适配。

把noFly设为`false`或者`remove`是允许飞行，设置为`true`是禁止飞行
